### ISSUE TITLE
Support `revert(string)` and `revert()` on Geth Nodes for `eth_call`

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/ethcontract-rs#92]
Geth and Ganache behave differently when an `eth_call` reverts. In Geth this is not treated as an RPC error while in Ganache (and presumably Parity) it is.

We want to extend the `ExecutionError` enum to have `Revert(Option<String>)` and `InvalidOpcode` error variants and make the errors consistent so that:
- `revert(string)` produces an `ExecutionError::Revert(Some(message))` on Geth and Ganache nodes for `eth_call` requests what revert with a message.
- `revert()` produces an `ExecutionError::Revert(None)` on Geth and Ganache nodes for `eth_call` requests that revert without a message.
- `invalid()` produces an `ExecutionError::InvalidOpcode` on Ganache nodes for `eth_call` requests that execute an `INVALID` opcode. Note that this is not supported for Geth as there is no good way to distinguish between `revert()` and `invalid()`.

Here is a table of `eth_call` responses from both Geth and Ganache:
```
Client  | revert(string)                        | revert()               | invalid()
--------+---------------------------------------+------------------------+-------------------------------
Geth    | Ok("0x08c379a0...")                   | Ok("0x")               | Ok("0x")
Ganache | Err({error: "revert", reason: "..."}) | Err({error: "revert"}) | Err({error: "invalid opcode"})
```

**Comment by nlordell** [comment]
Some sample RPC responses for unit tests:

### Geth `revert(string)`

```
{"jsonrpc":"2.0","id":1,"result":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001e636f6e7472616374207265766572746564206173207265717565737465640000"}
```

### Geth `revert()`/`invalid()`:

```
{"jsonrpc":"2.0","id":2,"result":"0x"}
```

### Ganache `revert(string)`:

```
{"id":1,"jsonrpc":"2.0","error":{"message":"VM Exception while processing transaction: revert contract reverted as requested","code":-32000,"data":{"0x991fef26454cd1b52e37041295833c24b883e03a2c654fd03bb67e66955e540b":{"error":"revert","program_counter":255,"return":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001e636f6e7472616374207265766572746564206173207265717565737465640000","reason":"contract reverted as requested"},"stack":"RuntimeError: VM Exception while processing transaction: revert contract reverted as requested\n    at Function.RuntimeError.fromResults (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/utils/runtimeerror.js:89:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/blockchain_double.js:548:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:74:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:969:1\n    at next (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:5225:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/state/cache.js:160:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/util.js:51:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:1\n    at done (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:246:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/database/levelupobjectadapter.js:110:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/async/dist/async.js:473:1\n    at iteratorCallback (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/async/dist/async.js:1064:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/async/dist/async.js:969:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/level-sublevel/shell.js:53:50\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/level-sublevel/nut.js:109:1","name":"RuntimeError"}}}
```

### Ganache `revert()`:

```
{"id":2,"jsonrpc":"2.0","error":{"message":"VM Exception while processing transaction: revert","code":-32000,"data":{"0x0dae2feb2ecc03b45fbe6eb40897876fa1b46600fff7ac8512bbdfcc4c352d17":{"error":"revert","program_counter":279,"return":"0x"},"stack":"RuntimeError: VM Exception while processing transaction: revert\n    at Function.RuntimeError.fromResults (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/utils/runtimeerror.js:89:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/blockchain_double.js:548:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:74:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:969:1\n    at next (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:5225:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/state/cache.js:160:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/util.js:51:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:1\n    at done (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:246:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/database/levelupobjectadapter.js:110:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/async/dist/async.js:473:1\n    at iteratorCallback (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/async/dist/async.js:1064:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/async/dist/async.js:969:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/level-sublevel/shell.js:53:50\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/level-sublevel/nut.js:109:1","name":"RuntimeError"}}}
```

### Ganache `invalid()`:

```
{"id":3,"jsonrpc":"2.0","error":{"message":"VM Exception while processing transaction: invalid opcode","code":-32000,"data":{"0x41f524480cc8c3561ff57d297e65e5c51326af54d4af335c52a31d953eee8152":{"error":"invalid opcode","program_counter":299,"return":"0x"},"stack":"RuntimeError: VM Exception while processing transaction: invalid opcode\n    at Function.RuntimeError.fromResults (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/utils/runtimeerror.js:89:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/blockchain_double.js:548:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:74:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:969:1\n    at next (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:5225:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/state/cache.js:160:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/util.js:51:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:1\n    at done (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:246:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/database/levelupobjectadapter.js:110:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/async/dist/async.js:473:1\n    at iteratorCallback (/home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/async/dist/async.js:1064:1)\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/ganache-core/node_modules/async/dist/async.js:969:1\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/level-sublevel/shell.js:53:50\n    at /home/nlordell/Developer/TEST/node_modules/truffle/build/webpack:/node_modules/level-sublevel/nut.js:109:1","name":"RuntimeError"}}}
```
